# Generated by Django 2.1.2 on 2018-11-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Moderator',
        ),
    ]
