# Generated by Django 2.1.2 on 2018-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_organization_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date_Time',
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
