# Generated by Django 2.1.2 on 2018-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181112_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Time',
            field=models.TimeField(),
        ),
    ]
